builds:
  - binary: stor-cli
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
nfpm:
  vendor: Avast Software
  homepage: https://github.com/avast/stor-client
  maintainer: Jan Seidl <seidl@avast.com>
  description: Stor CLI.
  license: MIT
  formats:
    - deb
    - rpm
archive:
  format_overrides:
    - goos: windows
      format: zip
