language: go
go: 1.8
install: make setup
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.txt
  - test -n "$TRAVIS_TAG" && gem install fpm && curl -sL http://git.io/goreleaser | bash
