[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.5"

[[constraint]]
  name = "github.com/avast/retry-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/avast/hashutil-go"
  branch = "more_generic_hashutil"
